services:
  welcome-page:
    image: httpd:latest
    restart: unless-stopped
    container_name: welcome-page

    networks:
      - docker-network

    volumes:
      - ./html:/usr/local/apache2/htdocs/

networks:
  docker-network:
    external: true
