services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:13
    restart: unless-stopped
    container_name: forgejo

    # ports:
    #   - '3000:3000'
    #   - '22:22'

    networks:
      - docker-network

    environment:
      - USER_UID=1000
      - USER_GID=1000

    volumes:
      - /srv/docker/volumes/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  docker-network:
    external: true

