services:
  enclosed:
    image: corentinth/enclosed
    restart: unless-stopped

    ports:
      - 8787:8787

    networks:
      - docker-network

    volumes:
      - /srv/docker/volumes/enclosed/enclosed-data:/app/.data

    environment:
      AUTHENTICATION_JWT_SECRET: ${AUTHENTICATION_JWT_SECRET}

networks:
  docker-network:
    external: true

