services:
  ntopng:
    image: ntop/ntopng:community
    restart: unless-stopped
    container_name: ntopng

    ports:
      - "3006:3000"  # Web interface port
      # - "3001:3001"  # Flow data (optional)

    networks:
      - docker-network

    environment:
      - NTOPNG_USER=${NTOPNG_USER}
      - NTOPNG_PASS=${NTOPNG_PASS}
      - NTOPNG_HOST=0.0.0.0              # Listen on all interfaces
      - NTOPNG_INTERFACE=all              # Monitor all interfaces

    volumes:
      - /srv/docker/volumes/ntopng/ntopng_data:/var/lib/ntopng

networks:
  docker-network:
    external: true
