services:
  translite:
    image: git.bloat.cat/gospodin/translite:master
    restart: unless-stopped
    container_name: translite

    # ports:
    #   - "127.0.0.1:8080:8080"

    networks:
      - docker-network

    security_opt:
      - no-new-privileges=true

    cap_drop:
      - ALL

networks:
  docker-network:
    external: true
