services:
  backup-upload-server:
    restart: unless-stopped
    container_name: backup-upload-server

    build:
      context: ./backup_upload_server/
      dockerfile: Dockerfile

    env_file: .env

    expose:
      - 8080

    networks:
      - docker-network

    environment:
      token: ${token}
      max_files: ${max_files}
      max_file_size_GB: ${max_file_size_GB}

    volumes:
      - /srv/docker/backups_uploaded:/app/uploads

networks:
  docker-network:
    external: true
