services:
  cryptpad:
    image: cryptpad/cryptpad:latest
    restart: unless-stopped
    container_name: cryptpad

    # ports:
    #   - '3001:3000'
    #   - '3003:3003'

    networks:
      - docker-network

    environment:
      - USER_UID=4001
      - USER_GID=4001
      - CPAD_MAIN_DOMAIN=https://cryptpad.lasercata.com
      - CPAD_SANDBOX_DOMAIN=https://sandbox.cryptpad.lasercata.com
      - CPAD_CONF=/cryptpad/config/config.js

    volumes:
      - /srv/docker/volumes/cryptpad/data/blob:/cryptpad/blob
      - /srv/docker/volumes/cryptpad/data/block:/cryptpad/block
      - /srv/docker/volumes/cryptpad/customize:/cryptpad/customize
      - /srv/docker/volumes/cryptpad/data/data:/cryptpad/data
      - /srv/docker/volumes/cryptpad/data/files:/cryptpad/datastore

networks:
  docker-network:
    external: true

